//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Chat.h
//  Source: ../../idl/Chat.idl
//  Generated: Sat Jun  4 21:35:03 2016
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _CHAT_H_
#define _CHAT_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace Chat
{
   struct ChatMessage;
   struct NameService;
   struct NamedMessage;
   const DDS::Long MAX_NAME = (DDS::Long) 32L;
   typedef DDS::Char* nameType;
   typedef DDS::String_var nameType_var;
   typedef DDS::String_out nameType_out;

   struct ChatMessage
   {
         DDS::Long userID;
         DDS::Long index;
         DDS::String_mgr content;
   };

   typedef DDS_DCPSStruct_var < ChatMessage> ChatMessage_var;
   typedef DDS_DCPSStruct_out < ChatMessage> ChatMessage_out;

   struct NameService
   {
         DDS::Long userID;
         DDS::String_mgr name;
   };

   typedef DDS_DCPSStruct_var < NameService> NameService_var;
   typedef DDS_DCPSStruct_out < NameService> NameService_out;

   struct NamedMessage
   {
         DDS::Long userID;
         DDS::String_mgr userName;
         DDS::Long index;
         DDS::String_mgr content;
   };

   typedef DDS_DCPSStruct_var < NamedMessage> NamedMessage_var;
   typedef DDS_DCPSStruct_out < NamedMessage> NamedMessage_out;
}




#endif 
